# Use postgres/example user/password credentials
version: "3.8"

services:
  client:
    build: .
    image: client_app:1.3.0-apline
    container_name: client-app
    restart: unless-stopped
    ports:
      - "${REACT_APP_PORT}:3000"
    environment:
      - WDS_SOCKET_PORT=0
    networks:
      - mynet

networks:
  mynet:
